# path to the checkpoint file containing the model
model_path: 3dunet/last_checkpoint.pytorch
# Should the patches be stored in memory or written directly to H5 during prediction.
# Set to True if you have enough RAM cause it's way faster
store_predictions_in_memory: True
# model configuration
model:
  # model class
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: crg
  # feature maps scale factor
  f_maps: 32
  # basic module
  basic_module: DoubleConv
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
# specify the test datasets
datasets:
  # patch size given to the network (adapt to fit in your GPU mem)
  patch: [32, 64, 64]
  # stride between patches (make sure the the patches overlap in order to get smoother prediction maps)
  stride: [8, 16, 16]
  # path to the raw data within the H5
  raw_internal_path: raw
  # how many subprocesses to use for data loading
  num_workers: 0
  # paths to the datasets
  test_path:
    - 'dane\256_h5\1.h5'
    - 'dane\256_h5\2.h5'
    # - resources/Normal001.h5
  all_data_path:
    - 'dane\256_h5\'
  save_path:
    - 'wyniki\predictions\'
  save_dcm_path:
    - 'wyniki\dicom\'
  path_to_random_dcm:
    - 'wyniki\dicom\random.dcm'
  transformer:
    test:
      raw:
        - name: Normalize
        - name: ToTensor
          expand_dims: true